### ISSUE TITLE
link to changeset on github for commits.

### ISSUE THREAD

**Issue by dsisnero** [ruby/b.r-l.o#120]
revisions view should link to the github commit.  For example:

https://bugs.ruby-lang.org/projects/ruby-master/repository/git/revisions/92449e0e99ae0e44f0deec5e59a7146824872952

should have a link on page to:

https://github.com/ruby/ruby/commit/92449e0e99ae0e44f0deec5e59a7146824872952

**Comment by hsbt** [comment]
I don't think so. 

We can see diff with https://bugs.ruby-lang.org/projects/ruby-master/repository/git/revisions/92449e0e99ae0e44f0deec5e59a7146824872952/diff

or 

https://git.ruby-lang.org/ruby.git/commit/?id=92449e0e99ae0e44f0deec5e59a7146824872952

I prefer to use git.ruby-lang.org link because it's ultra fast.
